### ISSUE TITLE
Open Source Friday 23/09/2022

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#11501]
Here are the things we want to focus on today - please join us in #t-product on Slack (https://mautic.org/slack) if you would like to join us!

Instructions for testing in the browser with Gitpod: https://contribute.mautic.org/contributing-to-mautic/tester#the-easy-way-using-gitpod

### Mautic 5 prioritised PRs

- [ ] [Check you can upload and preview an asset](https://github.com/mautic/mautic/pull/11145) - needs tests and code review
- [ ] [Check you can execute bin/console --version](https://github.com/mautic/mautic/pull/11138) - needs code review

### Mautic 4.4.3 prioritised PRs

The release is on Monday, so let's get these merged!

- [ ] 🐛 Bug fix [Hubspot API authorization type](https://github.com/mautic/mautic/pull/11470) - one more test and code review
- [x] 🐛 Bug fix [Fix JS error when pause preference centre setting is turned off](https://github.com/mautic/mautic/pull/11431) - one more test and code review
- [x] 🐛 Bug fix [Fix unique clicks in focus items](https://github.com/mautic/mautic/pull/11418) - one more test and code review
- [ ] 🐛 Bug fix [Fix date empty/not empty company segment filters](https://github.com/mautic/mautic/pull/11411) - one more test and code review
- [ ] 🐛 Bug fix [Fix for catch-all and forwarding addresses in Outlook not receiving all mails](https://github.com/mautic/mautic/pull/11400) - one more test and code review
- [x] 🐛 Bug fix [Fix for CSRF errors](https://github.com/mautic/mautic/pull/10567) - one more test and code review

#### Bug fixes

- [ ] 🐛 Bug fix [Fix select and boolean fields with email dynamic content](https://github.com/mautic/mautic/pull/11393) - test and code review needed
- [x] 🐛 Bug fix [Fix handling of not-parsable URL's in page tracking model](https://github.com/mautic/mautic/pull/11500) - test needed
- [x] 🐛 Bug fix [Fix the best read hours dashboard widget when filtering by segment](https://github.com/mautic/mautic/pull/11485) - code review needed
- [ ] 🐛 Bug fix [Fix permissions on Dynamic Content - 5.x branch](https://github.com/mautic/mautic/pull/11480) and [Fix permissions on Dynamic Content - 4.4 branch](https://github.com/mautic/mautic/pull/11278) - test and code review needed
- [ ] 🐛 Bug fix [Fix segment filter error when drag&dropping multiple times](https://github.com/mautic/mautic/pull/11434) - one more test and code review needed

#### Enhancements
- [x] 🚀 Enhancement [Add locks to prevent commands being run if already in progress](https://github.com/mautic/mautic/pull/11478) - needs tests and code review
- [x] 🚀 Enhancement [Track clicks on mailtto: links in emails](https://github.com/mautic/mautic/pull/11481) - one test and code review needed
- [ ] 🚀 Enhancement [Add images/badges/icons to web notifications](https://github.com/mautic/mautic/pull/11395)

### Bugs to fix

- [ ] [Unable to send segment emails on 5.x branch ](https://github.com/mautic/mautic/issues/11490)
- [ ] [Segment member contact list not loading in tab 4.4.1](https://github.com/mautic/mautic/issues/11475)
- [ ] [Landings pages and emails created via the fixtures are broken](https://github.com/mautic/mautic/issues/11471)

#### Outstanding refactoring work

- [ ] The NumberToLocalizedStringTransformer::ROUND_* constants have been deprecated, use \NumberFormatter::ROUND_* instead. [TPROD-303](https://mautic.atlassian.net/browse/TPROD-303)
- [ ] Deprecated LogoutHandlerInterface, register a listener on the LogoutEvent event instead. [TPROD-304](https://mautic.atlassian.net/browse/TPROD-304)

**Comment by mautibot** [comment]
This issue has been mentioned on **Mautic Community Forums**. There might be relevant details there:

https://forum.mautic.org/t/join-us-today-in-open-source-friday/25494/1
