### ISSUE TITLE
Roadmap to 5.0-alpha release

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#11540]
Mautic 5 will be the next major release for Mautic, bringing support for Symfony 5, PHP 8.1 and some new features.

This issue serves as a tracker for all the things that need to be completed for us to release the alpha for testing.

## Mandatory code updates

We have to deal with all the deprecations and removals that come with Symfony 5. These are the outstanding ones that we need help with:

### 👀  Outstanding refactoring work

These are for Symfony 5.2 support so can be nudged to the beta release if necessary.

- [x] Deprecated LogoutHandlerInterface, register a listener on the LogoutEvent event instead. [TPROD-304](https://mautic.atlassian.net/browse/TPROD-304) #[11867](https://github.com/mautic/mautic/pull/11867)

## ☑️ Outstanding tasks to be completed

These are Mautic-specific things that we need to do before we can make the release. They may have sub-tasks - please check the links for more details.

- [ ] Remove UI based upgrade [TPROD-341](https://mautic.atlassian.net/browse/TPROD-341)
- [ ] Get Mautic working on Symfony 5 [TPROD-342](https://mautic.atlassian.net/browse/TPROD-342)
- [ ] Remove support for PHP 7.4 and implement support for PHP 8.1 [TPROD-345](https://mautic.atlassian.net/browse/TPROD-345)

## 🔎  PRs to review and test

This is work that has already been done and we need your help to get them over the finish line 🏁 . Read how to test PR's here: [https://contribute.mautic.org/contributing-to-mautic/tester#the-easy-way-using-gitpod](https://contribute.mautic.org/contributing-to-mautic/tester#the-easy-way-using-gitpod)

- [ ] https://github.com/mautic/mautic/pull/11613
- [ ] https://github.com/mautic/mautic/pull/11729
- [ ] https://github.com/mautic/mautic/pull/11613 
- [ ] https://github.com/mautic/mautic/pull/12181

## 🚧  WIP (with owners working on it mentioned)

These are not yet ready for testing - maybe they have conflicts to be resolved or outstanding feedback/more work to be done - but they will be coming soon. The mentioned people are the main folks who are leading on those tasks/issues.

- [x] [Replace Swiftmailer with Symfony Mailer](https://github.com/mautic/mautic/pull/11180) @mabumusa1 @escopecz 
- [x]  [Fix limit/batch for the broadcast email command](https://github.com/mautic/mautic/pull/11127) @kuzmany 
- [x] [Refactor Event classes to Contracts and make dispatcher as first argument TPROD-275/276](https://github.com/mautic/mautic/pull/11140) @kuzmany 
- [x] [TPROD-292 large refactoring for Symfony 5](https://github.com/mautic/mautic/pull/11141) @kuzmany @escopecz 
- [x] [Refactor all the things to use Twig instead of PHP TPROD-232](https://mautic.atlassian.net/browse/TPROD-232) @SalemCode8
- [x] Fix issues with Composer based installations ref. file locations [Separate assets from media](https://github.com/mautic/mautic/pull/10682) + PR to come for configuration directory location @mollux
- [x] ~~Fix issues with Composer based installations ref. asset generation [Removing production assets from Composer builds](https://github.com/mautic/mautic/pull/10655) and [Generate production assets on composer install/update](https://github.com/mautic/mautic/pull/9736) @mollux~~  https://github.com/mautic/mautic/pull/11865 is a replacement for the two other PRs

### Documentation

Please liaise with @fakela and @favour-chibueze if you would like to help with these tasks!

- [ ] Remove references to UI based upgrades
- [ ] Improve documentation on command line updates
- [ ] Improve documentation on Composer installation and upgrade
- [ ] Create a 'what's new' page

### Marketing

Please liaise with @tobsowo and @deborahsalves if you would like to help with these tasks!

- [ ] [Create a release theme](https://mautic.atlassian.net/browse/TMAR-190)
- [ ] [Write promos for alpha release](https://mautic.atlassian.net/browse/TMAR-107)
- [ ] [Write promos for beta release](https://mautic.atlassian.net/browse/TMAR-106)
- [ ] [Write promos for Release Candidate release](https://mautic.atlassian.net/browse/TMAR-105)
- [ ] [Write promos for General Availability release](https://mautic.atlassian.net/browse/TMAR-104)

[TPROD-303]: https://mautic.atlassian.net/browse/TPROD-303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TPROD-304]: https://mautic.atlassian.net/browse/TPROD-304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TPROD-341]: https://mautic.atlassian.net/browse/TPROD-341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TPROD-342]: https://mautic.atlassian.net/browse/TPROD-342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by mautibot** [comment]
This issue has been mentioned on **Mautic Community Forums**. There might be relevant details there:

https://forum.mautic.org/t/friday-the-best-day-of-the-week-join-us-for-open-source-friday-to-help-make-mautic-more-awesome/25611/1

**Comment by mautibot** [comment]
This issue has been mentioned on **Mautic Community Forums**. There might be relevant details there:

https://forum.mautic.org/t/your-opportunity-to-help-get-more-bug-fixes-and-features-into-mautic/25689/1

**Comment by mautibot** [comment]
This issue has been mentioned on **Mautic Community Forums**. There might be relevant details there:

https://forum.mautic.org/t/its-friday-time-to-give-something-back-to-mautic/25768/1

**Comment by mautibot** [comment]
This issue has been mentioned on **Mautic Community Forums**. There might be relevant details there:

https://forum.mautic.org/t/q4-2022-mautic-community-roundup/26692/1

**Comment by maximejobin** [comment]
Any link to better understand the Mautic 5 release schedule. All I find is a release in January 2023 but we are passed this date and cannot find any info on the new target (if there is any).

**Comment by npracht** [comment]
Hello Maxime !
The latest official communication is this one: https://www.mautic.org/blog/community/update-mautic-5-release-schedule

If you'd like to help, feel free to carry any of the listed points above. 

Thanks !

**Comment by maximejobin** [comment]
> We are aiming for a Release Candidate in December, with General Availability in January 2023 assuming the support from the community with testing and reviewing.

Is it released? I cannot find any 5.0 version (RC or GA) and it's 2 months later... Am I misunderstanding something?

**Comment by RCheesley** [comment]
If you look above you'll see multiple outstanding tasks.

It won't be released until they're completed.

Please join us in #t-product on Slack if you'd like to help get it released sooner, we're very short on people helping to test which is holding up progress. All testing can be done by anyone who knows how to use Mautic, in the web browser. No technical knowledge needed.

**Comment by mautibot** [comment]
This issue has been mentioned on **Mautic Community Forums**. There might be relevant details there:

https://forum.mautic.org/t/update-on-mautic-5/27064/1

**Comment by mautibot** [comment]
This issue has been mentioned on **Mautic Community Forums**. There might be relevant details there:

https://forum.mautic.org/t/towards-a-future-of-independence/27741/14

**Comment by kevin25** [comment]
Can you allow to send with different domain emails?
