### ISSUE TITLE
Open Source Friday 07/10/2022

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#11551]
Here are the things we want to focus on today - please join us in #t-product on Slack (https://mautic.org/slack) if you would like to join us!

Instructions for testing in the browser with Gitpod: https://contribute.mautic.org/contributing-to-mautic/tester#the-easy-way-using-gitpod

### Mautic 5 prioritised PRs

- [x] [Check you can upload and preview an asset](https://github.com/mautic/mautic/pull/11145) - needs tests and code review
- [x] [Check you can execute bin/console --version](https://github.com/mautic/mautic/pull/11138) - needs code review
- [x] [Try to merge contacts via API, check importing contacts, check the UI, make sure page hits are working](https://github.com/mautic/mautic/pull/11543) - needs testing and code review

#### Bug fixes

- [ ] 🐛 Bug fix [Hubspot API authorization type](https://github.com/mautic/mautic/pull/11470) - one more test and code review
- [x] 🐛 Bug fix [Fix date empty/not empty company segment filters](https://github.com/mautic/mautic/pull/11411) - one more test and code review
- [x] 🐛 Bug fix [Fix for catch-all and forwarding addresses in Outlook not receiving all mails](https://github.com/mautic/mautic/pull/11400) - one more test and code review

#### Enhancements
- [ ] 🚀 Enhancement [Add images/badges/icons to web notifications](https://github.com/mautic/mautic/pull/11395) - needs testing and code review
- [x] 🚀 Enhancement [Add Mautic tokens to editor in GrapesJS builder](https://github.com/mautic/mautic/pull/11525) - one more test and code review
- [x] 🚀 Enhancement [Add stage information to export data](https://github.com/mautic/mautic/pull/11552)

### Bugs to fix

- [ ] [Unable to send segment emails on 5.x branch ](https://github.com/mautic/mautic/issues/11490)
- [ ] [Segment member contact list not loading in tab 4.4.1](https://github.com/mautic/mautic/issues/11475)
- [ ] [Landings pages and emails created via the fixtures are broken](https://github.com/mautic/mautic/issues/11471)

#### Outstanding refactoring work

- [ ] The NumberToLocalizedStringTransformer::ROUND_* constants have been deprecated, use \NumberFormatter::ROUND_* instead. [TPROD-303](https://mautic.atlassian.net/browse/TPROD-303)
- [ ] Deprecated LogoutHandlerInterface, register a listener on the LogoutEvent event instead. [TPROD-304](https://mautic.atlassian.net/browse/TPROD-304)

**Comment by mautibot** [comment]
This issue has been mentioned on **Mautic Community Forums**. There might be relevant details there:

https://forum.mautic.org/t/friday-the-best-day-of-the-week-join-us-for-open-source-friday-to-help-make-mautic-more-awesome/25611/1
