### ISSUE TITLE
Open Source Friday 14/10/2022

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#11590]
Here are the things we want to focus on today - please join us in #t-product on Slack (https://mautic.org/slack) if you would like to join us!

Instructions for testing in the browser with Gitpod: https://contribute.mautic.org/contributing-to-mautic/tester#the-easy-way-using-gitpod

#### The big PHP to Twig migration - PRs to review/test

- [x] 🔧 Refactoring [Check everything works with stages](https://github.com/mautic/mautic/pull/11565)
- [ ] ~🔧 Refactoring [Check everything works with Users](https://github.com/mautic/mautic/pull/11580)~ - pending feedback from developer

#### Bug fixes

- [ ] 🐛 Bug fix [Hubspot API authorization type](https://github.com/mautic/mautic/pull/11470) - one more test and code review
- [x] 🐛 Bug fix [Fix issue with remove from campaign / restart campaign](https://github.com/mautic/mautic/pull/11573) - needs tests and code review
- [x] 🐛 Bugfix [Fix jump to event without parent causing endless loop](https://github.com/mautic/mautic/pull/11568) - Needs tests and code review
- [ ] 🐛 Bugfix [Fix chart on email view showing one day early](https://github.com/mautic/mautic/pull/11544) - one more test and code review
- [x] 🐛 Bugfix [Fix reports with aggregated columns not saving](https://github.com/mautic/mautic/pull/11538) - needs testing
- [x] 🐛 Bugfix [Fix double loading of custom fields when using sample data](https://github.com/mautic/mautic/pull/11536) - needs testing

#### Enhancements

- [x] 🚀 Enhancement [Compress Webhooks queue payload](https://github.com/mautic/mautic/pull/11589) - needs testing and code review
- [ ] 🚀 Enhancement [Optimized query for getting orphaned leads in a segment](Optimized query for getting orphaned leads in a segment) - needs testing and code review
- [ ] 🚀 Enhancement [Add form results as data source for reports](https://github.com/mautic/mautic/pull/11567) - needs testing

### Bugs to fix

- [ ] [Unable to send segment emails on 5.x branch ](https://github.com/mautic/mautic/issues/11490)
- [ ] [Segment member contact list not loading in tab 4.4.1](https://github.com/mautic/mautic/issues/11475)
- [ ] [Landings pages and emails created via the fixtures are broken](https://github.com/mautic/mautic/issues/11471)

#### Outstanding refactoring work

- [ ] The NumberToLocalizedStringTransformer::ROUND_* constants have been deprecated, use \NumberFormatter::ROUND_* instead. [TPROD-303](https://mautic.atlassian.net/browse/TPROD-303)
- [ ] Deprecated LogoutHandlerInterface, register a listener on the LogoutEvent event instead. [TPROD-304](https://mautic.atlassian.net/browse/TPROD-304)

**Comment by mautibot** [comment]
This issue has been mentioned on **Mautic Community Forums**. There might be relevant details there:

https://forum.mautic.org/t/your-opportunity-to-help-get-more-bug-fixes-and-features-into-mautic/25689/1
