### ISSUE TITLE
New buttons design with hierarchy

### ISSUE THREAD

**Issue by andersonjeccel** [mautic/mautic#13146]
### Description
Create a new button design with a clear hierarchy to visually distinguish and prioritize actions within the platform's user interface.

Based on user feedback:

> Differentiate in CTA's: have primary, secondary and tertiary CTA's styled differently

> Make the actions stand out

### Impact
The implementation of a new button design with hierarchy will improve user navigation and interaction, aiding in the prioritization of actions and enhancing the overall user experience by providing a more intuitive and organized interface.

## Tasks

Create the CSS:
- [x] Primary
- [x] Secondary
- [x] Tertiary
- [x] Ghost
- [ ] Icon only
- [x] Pagination

Adjust everywhere:

- [x] Dashboard
- [x] Account page
- [x] Contact creation
- [ ] Contact edit pages
- [ ] Company creation
- [ ] Company edit pages
- [ ] Campaign builder
- [ ] Review everything to make sure it's all done

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by andersonjeccel** [comment]
Done in #13770
