### ISSUE TITLE
New dropdown design

### ISSUE THREAD

**Issue by andersonjeccel** [mautic/mautic#13152]
### Description
The existing dropdown design lacks visual appeal and user-friendliness; we seek to implement a new, more attractive and user-centric dropdown design.

### Impact
Introducing the new dropdown design will enhance the overall aesthetic and usability of the interface, leading to improved user engagement and satisfaction.

---

### Tasks

- [ ] Redesign the normal dropdown
- [ ] Redesign calendar dropdown
- [ ] Redesign fields dropdown

<br /><hr>
Care about this issue? Want to get it resolved sooner? If you are a <a href='https://www.mautic.org/become-a-member-of-mautic'>member of Mautic</a>, you can add some funds to the <a href='https://opencollective.com/mautic/projects/bounties'>Bounties Project</a> so that the person who completes this task can claim those funds once it is merged by a member of the core team! Read the docs <a href='https://contribute.mautic.org/product-team/mautic-bounty-programme'>here.</a>

**Comment by RCheesley** [comment]
Still relevant

**Comment by andersonjeccel** [comment]
Done
