### ISSUE TITLE
Completely new dashboard experience

### ISSUE THREAD

**Issue by andersonjeccel** [mautic/mautic#13166]
### Description
We have to revamp and modernize the existing dashboard interface with a fresh design and enhanced functionality.

Users would like to see essential information easier.

### Impact
This update will improve user engagement, streamline navigation, and provide a more intuitive user experience.

---

## Tasks

- [ ] Search for the best references
- [ ] Create a prototype for the idea
- [ ] New dropdown icon for cards
- [ ] New cards style
