### ISSUE TITLE
Make installation/upgrade scripts more robust for different environments

### ISSUE THREAD

**Issue by dennisameling** [mautic/mautic#8452]
[//]: # ( Invisible comment: 
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Before you create the issue:
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII
Search for similar report among other reported issues.
Learn how to troubleshoot at https://www.mautic.org/docs/en/tips/troubleshooting.html
Use drag&drop to attach images or other files )

## Bug Description
Some users are having issues with folder permissions or other things while upgrading Mautic. Some examples:
- https://mautic.slack.com/archives/C02GEN0SG/p1581616895189100 (follow-up: https://mautic.slack.com/archives/C02GEN0SG/p1581622999191300)
- https://forum.mautic.org/t/server-500-error-after-2-16-0-update-attempt/12827/8
- TODO add more examples here

There doesn't seem to be any form of Mautic documentation on which folders should be writable in order to upgrade Mautic. What also needs to be considered is that we currently have 2 ways of upgrading Mautic:
- Through the CLI (CLI user needs to have write permissions)
- Through the UI (webserver needs to have write permissions)

... so for some users, a CLI upgrade might succeed (when the CLI user has proper write permissions) while a UI upgrade might not (when the webserver doesn't have proper write permissions)

This issue is to track work for the following things:

- [ ] Check the maximum execution PHP time with `ini_get('max_execution_time')`, if this is not at least 3 minutes (TODO check if this is enough) or if the amount of contacts is >10,000 (TODO check what threshold we should have here) then prevent the user from upgrading through the UI.
- [ ] Check if the user uses the official Mautic package or if they cloned from GitHub prior to upgrading and/or installing. The official package contains the right Composer dependencies out of the box, while with the GitHub source code there might be some issues when upgrading (e.g. see [this thread](https://forum.mautic.org/t/server-500-error-after-2-16-0-update-attempt/12827/10)). 
- [ ] Find out whether the CLI and UI upgrade scripts do folder permissions checks **before** starting an upgrade (apparently it already does when doing a clean installation: https://forum.mautic.org/t/directory-must-be-writable/5288)
- [ ] Document which folders should be writable by Mautic during a clean install or upgrade (according to the Getting Started guide the whole Mautic folder should be writable by doing a `chown` on it https://www.mautic.org/docs/en/setup/getting_started.html#file-ownership), is this correct or can this lead to security issues? Also refer to "[the dangers of 777](https://wordpress.org/support/article/changing-file-permissions/#the-dangers-of-777)" by WordPress
- [ ] If no pre-upgrade folder permissions checks are in place, they can be built, to ensure more users will have a smoother upgrade experience.
- [ ] Test clean install with read-only permissions to see what errors Mautic shows to the user
- [ ] Test CLI upgrade with read-only permissions to see what errors Mautic shows to the user
- [ ] Test UI upgrade with read-only permissions to see what errors Mautic shows to the user
- [ ] Show warning in UI if one or more required crons haven't ran for an X amount of time
- [ ] Check if the user has the correct DB versions in the installation process (e.g. MySQL 5.7.x or MariaDB 10.2.x)

| Q   | A
| --- | ---
| Mautic version | N/A
| PHP version | N/A
| Browser | N/A

[//]: # ( Invisible comment:
Please check for related errors in the latest log file in [mautic root]/app/log/ and/or the web server's logs and post them here. Be sure to remove sensitive information if applicable. )

**Comment by mautibot** [comment]
This issue has been mentioned on **Mautic Community Forums**. There might be relevant details there:

https://forum.mautic.org/t/server-500-error-after-2-16-0-update-attempt/12827/12

**Comment by mautibot** [comment]
This issue has been mentioned on **Mautic Community Forums**. There might be relevant details there:

https://forum.mautic.org/t/server-500-error-after-2-16-0-update-attempt/12827/16

**Comment by RCheesley** [comment]
I made a start by adding some documentation on:

- PHP restrictions: https://docs.mautic.org/en/troubleshooting/working-with-php-ini-resource-limits
- File and folder permissions: https://docs.mautic.org/en/troubleshooting/file-ownership-and-permissions

These could be expanded to include 'best practice' values/settings.

**Comment by RCheesley** [comment]
Leaving this one open for now - would be nice to get this rolled into 3.1 if possible!  It might be a nice one for the Season of Docs candidates to work on if we add an issue in Mautic/mautic-documentation

**Comment by RCheesley** [comment]
This will form part of the install/upgrade improvement initiative so I've tagged it provisionally for 3.3 to be discussed in the kick-off call.

**Comment by khadar1020** [comment]
I would like to contribute to this issue
