### ISSUE TITLE
Q1 2021 Mautic Community Roadmap

### ISSUE THREAD

**Issue by RCheesley** [mautic/mautic#9656]
The goal of this quarterly roadmap is to provide clarity for the Mautic Community Teams and our wider community about our priorities for the next 3 months.  This will also be shared in the forums to ensure that we reach the widest possible audience.

Over time we expect to be planning further ahead, but for now we will start with one quarter at a time. While these are the projects and tasks we'll be focusing on, life happens and iterations might take place.

We have included, where appropriate, information about how you can contribute to these projects and tasks. Many are very **significantly under-resourced** at present and would **very** much value your involvement.

NOTE: All meetings are featured on the [Mautic Community Calendar](https://calendar.google.com/calendar/u/0?cid=Y181cDd1azhlcTU1NHVnbXB1Zmx1amZhNmpob0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t) in addition to release dates, contribution weekends, office hours and meetups.

### Community Team

Team Lead: Ekke Guembel
Assistant Team Lead: Nico Grienauer
Slack: #t-community
Meetings: Async on Slack, every other Thursday at 1600hrs UTC

- [ ] **Centrally Organized Events: Make Global Mautic Conference happen online in Q2 (June 16/17)**
- Related issues [https://mautic.atlassian.net/browse/MCON-11](https://mautic.atlassian.net/browse/MCON-11)
- Related Confluence page [https://mautic.atlassian.net/wiki/spaces/MCON/overview](https://mautic.atlassian.net/wiki/spaces/MCON/overview)
    - [x] Publish date
    - [x] Decide on Platform
    - [x] Publish Call for Speakers by March 1st
    - [x] Finalize Sponsorship Packages and reach out for Sponsors
    - [x] Contact Training Day partners, and finalize Training Day outlines

- [ ] **Blueprint for Local Communities**
- Related issue https://mautic.atlassian.net/browse/TCOMM-27
- Related Confluence pages [https://mautic.atlassian.net/wiki/spaces/CT/pages/1409108/Local+community+efforts](https://mautic.atlassian.net/wiki/spaces/CT/pages/1409108/Local+community+efforts) 
[https://mautic.atlassian.net/wiki/spaces/CT/pages/8290306/Native+Communities+for+Mautic+-+PROPOSAL+- ](https://mautic.atlassian.net/wiki/spaces/CT/pages/8290306/Native+Communities+for+Mautic+-+PROPOSAL+- )
    - [ ] Draft document
    - [ ] Connect with Marketing for required resources
    - [ ] Reconnect to pilot local communities / potential leads
    - [ ] Prepare Blog post to be published no later than April

- [ ] **“Planet Mautic” curated news stream**
- Related issue https://mautic.atlassian.net/browse/TCOMM-29 
    - [ ] Implement necessary tech
    - [ ] Implement demo content (not necessarily published at this point)

- [ ] **Rules for Mautic places in Social Media**
- Related issues
[https://mautic.atlassian.net/browse/TCOMM-66](https://mautic.atlassian.net/browse/TCOMM-66), [https://mautic.atlassian.net/browse/TCOMM-68](https://mautic.atlassian.net/browse/TCOMM-68), [https://mautic.atlassian.net/browse/TCOMM-70](https://mautic.atlassian.net/browse/TCOMM-70) 
    - [ ] Draft “Rules for Mautic places in Social Media” document
    - [ ] Have list of existing groups, and describe per-case migration plan that avoids frictions
    - [ ] Get decision from Community team (involve leadership team)

### Education Team

Team Lead: Leon-Elias Oltmanns
Assistant Team Lead: Favour Kelvin
Slack: #t-education
Meetings: Async on Slack, every other Friday at 1200hrs UTC

- [ ]  **Documentation Improvements**
- Related issues [https://mautic.atlassian.net/secure/RapidBoard.jspa?rapidView=17&projectKey=TEDU&selectedIssue=TEDU-19](https://mautic.atlassian.net/secure/RapidBoard.jspa?rapidView=17&projectKey=TEDU&selectedIssue=TEDU-19)
    - [ ] Including the Mautic newest release feature in the docs
    - [ ] Work on open issues in the documentation (https://github.com/mautic/mautic-documentation/pull/42)

- [ ] **Knowledgebase Improvements**
- Related issues [https://mautic.atlassian.net/secure/RapidBoard.jspa?rapidView=17&projectKey=TEDU&selectedIssue=TEDU-19&search=KB](https://mautic.atlassian.net/secure/RapidBoard.jspa?rapidView=17&projectKey=TEDU&selectedIssue=TEDU-19&search=KB)
    -  [ ] Add more needed articles from mautic users to the KB
    -  [ ] Optimize the KB articles for SEO 
    -  [ ] Video tutorials on some Mautic topics  

### Legal & Finance Team

Team Lead - Vacant (Contact: Ruth Cheesley)
Assistant Team Lead - Vacant
Slack: #t-legal-finance

- [x] **Roll out the Bountysource integration with Github**
- Related issue/s: [https://mautic.atlassian.net/browse/TLF-33](https://mautic.atlassian.net/browse/TLF-33)
- Task owner: Ruth Cheesley 
- Status: Completed
    - [x] Leadership team sign off https://mautic.atlassian.net/browse/TLF-35 
    - [x] Blog post published https://mautic.atlassian.net/browse/TLF-37 
    - [x] Github integration enabled https://mautic.atlassian.net/browse/TLF-36 

- [ ] **Share the 2021-22 budget**
- Related issue/s: [https://mautic.atlassian.net/browse/TLF-38](https://mautic.atlassian.net/browse/TLF-38) 
- Task owner: Ruth Cheesley 
- Status: Draft budget has been prepared
	- [x] Finalise the 2021 budget
	- [ ] Draft a blog post to announce the budget
	- [x] Decide how to represent the budget spend against planned
	- [ ] Publish blog post and share in the community
	
- [x] **Review and update the financial policy to account for the bounty programme and funding of initiatives**
- Related issue/s: [https://mautic.atlassian.net/browse/TLF-43](https://mautic.atlassian.net/browse/TLF-43) 
- Task owner: Ruth Cheesley 
- Status: Not started
    - [x] Review the financial policy and determine if changes are required
    - [x] Review with Acquia finance team on any changes
    - [x] Publish updated financial policy 

### Marketing Team 

Team Lead: Radu Zlatianu
Assistant Team Lead: Oluwatobi Owolabi 
Slack: #t-marketing
Meetings: Async on Slack, every other Monday at 1800hrs UTC

- [ ] **Finish the setup and deploy the Mautic instance for Mautic.org.** 
- Related issue/s: https://mautic.atlassian.net/browse/TMAR-40
- Task owner: Laurine Augiron	
    - [ ] GDPR re-consent process
    - [ ] List import and cleaning
    - [ ] Setup and configuration of the instance
    - [ ] Start sending newsletters and announcements 1st of March

- [ ]  **Recruit into the team to have 6 actively contributing members (currently 4 - Radu, Oluwatobi, David & Laurine)**
- Task owner: Radu Zlatianu

- [ ]  **Content Marketing to start 1st of March with a clear plan and deliverables**
	- Task owner: David Schargle
	- Related issue/s: [https://mautic.atlassian.net/jira/software/c/projects/MTEC/issues/?filter=allissues](https://mautic.atlassian.net/jira/software/c/projects/MTEC/issues/?filter=allissues) 
    - [ ] Develop a content plan for the next two quarters
    - [ ] Recruit writers to contribute to the blog
    - [ ] Source, edit and publish two new content pieces

### Product Team
Team Lead: Norman Pracht
Assistant Team Lead (Development): Mohit Aghera
Assistant Team Lead (Product): Joey Keller
Slack: #t-product
Meetings: Async on Slack, every other Tuesday at 1300hrs UTC

- [ ] **Reduce pending PRs from 200 to less than 100 by testing ready to test PRs and adding tests to ready to test but missing tests.**
    - [x] Hold a contribution event in advance of each release and work with the Marketing Team to increase the number of contributors attending
    - [ ] Review and update the onboarding resources for new contributors

- [ ] **Synchronise and align release process with the Docker image to ensure that it remains up to date**
 
- [x] **Become a CNA so that we manage all security issues and assign CVE’s ourselves**
- Task owner: Ruth Cheesley 
- Status: In progress - Ruth Cheesley and Alan Hartless have undertaken the mandatory training and will shortly be moving to the next step in the process

#### Releases
- [x] **Develop themes for each minor release going forward and structure pending PR’s accordingly**

- [x] **Ensure that all releases are made according to the release schedule**

- [x] **Ensure that all merged PR’s meet the required quality standards (maintains or improves code coverage, has documentation where required)**

#### Builders Initiative
⚠️  Contributors are needed to support this initiative! ⚠️

Slack: #i-builders
Meetings: Every Thursday at 1500hrs on [Zoom](https://acquia.zoom.us/j/92425682047?pwd=M0NJamtVRERVK2Z5TFdWRlJ5a1RUZz09)

- [x] **Finalise the GrapeJS builder (email and landing page) for inclusion as an optional plugin in the 3.3 release**

- [x] **Work with the Education and Marketing teams to prepare documentation and tutorials for the 3.3 release**

- [ ] **Iterate on the initial release with the aim to have it ready for testing in the Mautic 4 pre-release packages (Mar-Apr) as the default browser**

- [ ] **Form a builders tiger team for ongoing management**

#### Composer Initiative

⚠️ Contributors are needed to support this initiative! ⚠️

Slack: #i-builders
Meetings: Every Wednesday at 0900hrs on [Zoom](https://acquia.zoom.us/j/97502038447?pwd=dXZ0dmFUMjBFbW9RK1dTKzl1WWNuZz09
)

Related Confluence page: https://mautic.atlassian.net/wiki/spaces/MI/pages/324337710/Composer+Support 
- [x] **Decide on folder structure that will be required for Composer Support**

- [x] **Prepare a first draft of the proposed implementation for review by the Core Team**

- [x] **Prepare PR for consideration in Mautic 4.0 release**

#### Install/upgrade initiative

⚠️ Contributors are needed to support this initiative! ⚠️

Slack: #i-install-upgrade

- [ ] **Implement checks from the Mautic 3 upgrade script into the install and upgrade**
- Related issue/s: https://github.com/mautic/mautic/issues/9607  
- Related Confluence page/s: https://mautic.atlassian.net/wiki/spaces/MI/pages/324435990/Improve+the+Installation+and+Upgrade+Process 
- Task owner: Ruth Cheesley 
- Status: Not started

	- [x] Write up the problem statement and identify useful resources
	- [ ] Find someone to work on implementation
	- [ ] Make a PR to be considered for the 3.3 or 4.0 releases

- [ ] **Improve documentation on the install and upgrade process**

- [ ] **Complete the missing parts of the Mautic 3.0 migration documentation and add resources for common errors**

#### Marketplace initiative

⚠️ Contributors are needed to support this initiative! ⚠️

Slack: #i-mautic-marketplace

- Related forum thread: https://forum.mautic.org/t/mautic-marketplace/12108
- Related Confluence page/s: https://mautic.atlassian.net/wiki/spaces/MI/pages/324436014/Mautic+Marketplace

- [x] **Create a PR implementation for a read-only beta marketplace allowing folk to test and provide feedback**
- Related PR: https://github.com/mautic/mautic/pull/9650 
- Task owner: John Linhart
- Status: In progress

- [x] **Work with the Composer initiative to ensure that proposals will be compatible with plans for the Marketplace**

#### Next Generation initiative

⚠️ Contributors are needed to support this initiative! In particular, developers with experience in Symfony, API Platform and Angular ⚠️

#i-mautic-next-generation

- [x] **Decouple two plugins from core and document the process for others to follow**

- [ ] **Proof of Concept for front-end (Angular)**

- [ ] **Proof of Concept for API Platform / Symfony 5 / Assets bundle**

#### Resource management initiative

⚠️ Contributors are needed to support this initiative! ⚠️

Slack: #i-resource-management

- [ ] **Build a team to work on the issues in the project scope**

- [ ] **Prepare a PR to implement the exporting of campaigns and associated resources**

- [ ] **Prepare a PR to implement the state of ‘archived’ for resources in Mautic and the associated views that will be required**

### Project-wide
- [x] **Develop a partners programme to showcase organisations who contribute to the community and offer Mautic services**
	- Task owner: Ruth Cheesley 
- Status: In progress

- [ ] **Publish a blog post highlighting the future roadmap, Strategic Initiatives and the ‘future of Mautic’**
- Task owner: Ruth Cheesley 
- Status: In Review

**Comment by nickveenhof** [comment]
#### Composer Initiative

:warning: Contributors are needed to support this initiative! :warning:

**Decide on folder structure that will be required for Composer Support**

Status: We're working this. It's actually a bit broader than a folder structure, but more a packagist / git repository structure issue. We're foreseeing repositories similar to the Drupal project. The team is working on a good local setup so we can reproduce the complexitites of packagist.org locally and test some structures out.

* **Prepare a first draft of the proposed implementation for review by the Core Team**
In progress

* **Prepare PR for consideration in Mautic 4.0 release**
To be started

**Comment by ekkeguembel** [comment]
### Community Team
**Mautic Conference**
* Visual Design overhauled
* Announcement published
* Sponsorship open
* Call for Papers published

**Local Communities**
* testing name / URLs
* Draft document in progress

**Comment by rzlatianu** [comment]
**Marketing Team**

**Mautic instance in tests**
currently testing

**Recruit into the team**
Joey Keller to join the team
5 members active (Radu, Oluwatobi, Laurine, David, Joey)

**Comment by fakela** [comment]
**EDUCATION TEAM**

**Google season of docs**: Proposal stage
Docs improvement
Multilingual inclusion in docs
More articles on the KB

**Current status:** in progress

**Comment by escopecz** [comment]
### Makretplace Initiative

The PR is here: https://github.com/mautic/mautic/pull/9650 together with a TODO list. It’s functional, can be tested. I have some more tests and docs to write. I’d very much appreciate some help with UI as we discussed. Screenshots attached in the PR description.
